name: test

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2.2.2
          with:
            python-version: 3.8
        - name: Install dependencies
          run: pip install pytest
        - name: run tests
          run: pytest
